// Thin loader around the wasm-pack output in ./wasm-pkg (generated by
// `npm run build:wasm`; not committed). Initialisation happens once and is
// shared by every caller.
import init, { status_line, target_arch, version } from './wasm-pkg/openpower_tools';

export interface WasmInfo {
  readonly version: string;
  readonly targetArch: string;
  readonly statusLine: string;
}

let ready: Promise<WasmInfo> | undefined;

export function loadWasm(): Promise<WasmInfo> {
  ready ??= init().then(() => ({
    version: version(),
    targetArch: target_arch(),
    statusLine: status_line(),
  }));
  return ready;
}
